### ISSUE TITLE
Escribir capítulos metodológicos de la memoria

### ISSUE THREAD

**Issue by dipzza** [dipzza/ultrastar-song2txt#15]
This chapters should have an overview of agile development and:

+ HUs
+ Milestones
+ Personas
+ CI
+ Explanation of how this leads to issues on milestones, to feature branches which after passing extensive CI go through review and then merge to main.

**Comment by JJ** [comment]
Conviene que plantees todos los issues, incluso este, como un problema, y todos, también estos, como cumpliendo una historia de usuario, en este caso #9. El informe es el PMV que presentas al tribunal.
