### ISSUE TITLE
Decide programming language

### ISSUE THREAD

**Issue by dipzza** [dipzza/ultrastar-song2txt#17]
When choosing a programming language, it is important to take into account its ease of reuse in other projects.

A low level language may be useful to interface with other languages (C, Rust, ...), a popular high level language to be used as a command line utility can be a good option too (Python, JS).

_Originally posted by @JJ in https://github.com/dipzza/ultrastar-song2txt/pull/12#discussion_r872642265_

User story affected: https://github.com/dipzza/ultrastar-song2txt/issues/10

**Comment by dipzza** [comment]
Some useful libraries for pitch estimation are available on Python (CREPE, pySpice, librosa, aubio, parselmouth, ...)

**Comment by JJ** [comment]
Please refer to the user story that's affected by this issue. Every issue must be related to a specific US (and milestone)

**Comment by dipzza** [comment]
User story affected #10

**Comment by JJ** [comment]
> User story affected #10

... in the body, if possible. You can simply edit it.

**Comment by JJ** [comment]
*Always* close from a commit.
