### ISSUE TITLE
Motivación del TFG

### ISSUE THREAD

**Issue by dipzza** [dipzza/ultrastar-song2txt#2]
Un TFG debe ser la solución a un problema usando medios informáticos. ¿Que problema pretende resolver este? ¿A quien ayudaría / quien lo usaría? ¿Cuál es la solución propuesta?

Las respuestas a esto deben incluirse en la Memoria en la sección de introducción.

**Comment by dipzza** [comment]
**Problema**
Existen múltiples programas de software libre similares a [SingStar](https://en.wikipedia.org/wiki/SingStar) ([ultrastar](https://github.com/UltraStar-Deluxe/USDX), [vocaluxe](https://github.com/Vocaluxe/Vocaluxe), [performous](https://github.com/performous/performous), ... ). Juegos de Karaoke en los que además de mostrarse la letra se da una puntuación a cada uno de los jugadores según la precisión que tenga al cantar las notas.

Las canciones se comparten en un formato de texto estandarizado que comparten todas las aplicaciones, pero adaptar una canción a este formato es complicado. 

El archivo de texto debe tener metadatos sobre la canción, BPM, letra separada por fonemas, en que segundo aparece cada fonema en la canción y la nota de cada fonema (lo que especialmente complicado si no hay archivos libres MIDI en internet o si el que está creando el archivo no posee experiencia musical).

**Usuarios**
En las comunidades de Karaoke hay usuarios que se dedican a crear canciones de forma regular, también otro usuarios encuentran el proceso demasiado complicado y hacen peticiones a otras personas de canciones o las votan en [listas de peticiones](https://ultrastar-es.org/es/canciones/peticiones). El objetivo del TFG sería tanto agilizar el trabajo de los que ya crean canciones como reducir la barrera de entrada para usuarios sin conocimiento músical.

**Solución propuesta**
Automatizar parte de la creación de una canción para karaoke a partir de información básica que se puede encontrar en un mp3 o pedir al usuario (nombre de la canción) y el propio audio.

**Comment by JJ** [comment]
En este issue has puesto varios caso de uso. Convendría que los convirtieras en historias de usuario.
Recordad que siempre hay una historia de usuario que se refiere al tribunal, sus actitudes y lo que quiere. En muchos casos sólo servirá para cambiar la memoria, pero puede que haya que desarrollar algo de infraestructura específica.
