### ISSUE TITLE
Task Runner

### ISSUE THREAD

**Issue by dipzza** [dipzza/ultrastar-song2txt#25]
Right now there is no easy way to check if code is gonna pass CI checks before pushing.

This tasks should be easily done locally too, so a defining them in a task runner would be useful. Also CI should use the task runner, to have only one source for defining the tasks.

**Comment by JJ** [comment]
You *really* don't need to pass CI before CI. Although, of course, a task runner is always needed and you need to justify its choice.

**Comment by dipzza** [comment]
CI is not using all task runner tasks.

Latex checks should stop using textidote-action and manually install textidote to be able to use makefile tasks.
Python checks should use make install.
