### ISSUE TITLE
Definir los perfiles de usuarios

### ISSUE THREAD

**Issue by dipzza** [dipzza/ultrastar-song2txt#5]
Es necesario clarificar a que clientes va dirigido el proyecto y así poder enfocarlo a resolver los problemas de estos.

Se utilizarán "role-based personas" (https://hpadkisson.medium.com/creating-role-based-personas-for-the-enterprise-6471e7060d82) creando grupos de individuos que realizan la misma función.

El criterio de aceptación es definir los grupos en la memoria, con información sobre ellos.

**Comment by dipzza** [comment]
Escribo aquí los perfiles que he visto por ahora:

1. Miembros del tribunal

Evaluan tanto el acto de defensa como la memoria presentada. Especialmente importantes ya que califican el 70% de la nota del proyecto.

Según los miembros que lo compongan estos pueden tener solo un conocimiento básico de ciertas areas o un conocimiento más avanzado y específico.

Al ser su principal trabajo es la evaluación del proyecto  es importante tener en cuenta lo que piden (útil consultar el artículo https://jj.github.io/que-es-un-trabajo-fin-de-x/tf.html) y facilitar la evaluación de los criterios de evaluación (https://grados.ugr.es/informatica/pages/infoacademica/tfg/evaluacion/plantillas-evaluacion-tfg-comision-evaluadora-xls/!)

2. Creadores de canciones para Karaoke

Adaptan canciones para poder usarlas en los juegos de Karaoke.

Serían los usuarios finales de las aplicaciones desarrolladas.

Es una actividad que hacen en su tiempo libre, por lo que pueden dejarla a medias o tener un tiempo limitado para realizarla.

No es requisito tener experiencia musical con ayuda de herramientas, pero es más complicado crear canciones para aquellos que no la tienen.

Suelen usar un ordenador de escritorio y tener un manejo medio de este.

3. Programadores / investigadores

Persona interesada en contribuir en el proyecto o utilizar alguna de sus partes para su propio trabajo.

Con conocimiento experto sobre herramientas de desarrollo y áreas de la informática.

Son usuarios tanto de la organización del proyecto / código como de partes de la documentación.

**Comment by JJ** [comment]
Si lo permite, si usas "notes" o "url". En general, una página web deberá usar "misc" o "Techrep", sin embargo.
