### ISSUE TITLE
No hay explicación de la terminología

### ISSUE THREAD

**Issue by dipzza** [dipzza/ultrastar-song2txt#50]
No sé si lo pusiste, pero sería conveniente que en la introducción pusieras una sección de terminología para que la gente entienda lo que es cada cosa.

_Originally posted by @JJ in https://github.com/dipzza/ultrastar-song2txt/pull/36#discussion_r957590691_

Los términos más extraños del ámbito informático suelen estar explicados cuando se usan, pero sobre todo la terminología musical no está definida. Relacionado con #9.

**Comment by dipzza** [comment]
Algunos términos no descritos:

- Nota
- Tono
- Frecuencia fundamental
- MIDI
- Pulsación
- Pulsaciones por minuto
- Fonema
- Software libre
- Software privativo
- API

**Comment by JJ** [comment]
Abreviaturas, también; a veces usas BPM para pulsaciones, ¿no?

**Comment by dipzza** [comment]
Creo que dejé de usar BPM como abreviatura porque me comentaste que no estaba definido, al ser una abreviatura inglesa y no española. Comento que en el formato UltraStar las pulsaciones por minuto tienen la etiqueta BPM, pero no uso BPM con el significado como tal. Igualmente cuando vaya a hacer esto le daré una lectura a la memoria y reviso si me estoy dejando algo.
